### ISSUE TITLE
uninitialized constant Puppet::Transport

### ISSUE THREAD

**Issue by PiR-B** [puppets-epic-show-theatre/puppet-nexus#55]
https://github.com/puppets-epic-show-theatre/puppet-nexus/commit/5c7a4501d988eed6dc518c47aa8ba30e1e0df250 seems to introduce a regression (lib/puppet/transport/nexus_rest_api.rb)

Error: /Stage[main]/Nexus::Config::Admin/Nexus_user[admin]: Could not evaluate: uninitialized constant Puppet::Transport

Test code :

```
  java::adopt { 'jdk8':
    ensure  => 'present',
    version => '8',
    java    => 'jdk',
  }
  -> class { 'nexus':
    version => '3.58.1-02',
    host => '0.0.0.0',
    download_site => 'https://download.sonatype.com/nexus/3',
    purge_default_repositories => true,
  }
```

Environment :
puppetserver: 8.1.0-1bullseye
puppet-agent: 8.1.0-1bullseye

**Comment by TuningYourCode** [comment]
should be fixed in main/master branch https://github.com/puppets-epic-show-theatre/puppet-nexus/pull/56
