### ISSUE TITLE
I cannot find a clear way to reopen the H2 database after Linux server shutdown

### ISSUE THREAD

**Issue by yasser583** [puppets-epic-show-theatre/puppet-nexus#70]
I'm doing some test on a server and it was shutdown without gracefully stopping Nexus. As a result, the H2 database got closed and I'm not able to make it work again. Here's a part of the log:

```
Error querying database.  Cause: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database has been closed [90098-224]
The error may exist in org/sonatype/nexus/internal/node/datastore/NodeIdDAO.xml
The error may involve defaultParameterMap
The error occurred while setting parameters
SQL: SELECT node_id FROM node_id WHERE id = 1;
```
Please your help.

**Comment by PiR-B** [comment]
Hi @yasser583,

Which version of pest-nexus module are you using ?
What is your Nexus version ?


This repository is intended for installing a Nexus instance.
For issues related to Nexus itself, I recommend reporting them directly on the Sonatype community at https://community.sonatype.com/ or https://github.com/sonatype/nexus-public

You'll find more specific help and experts who can better address your questions there.


Regards

**Comment by yasser583** [comment]
Hello @PiR-B, I'm using 4.1.0 which is the latest for Nexus version 3.71.0 which is also the latest. So far everything is going well with pest-nexus.
I'll check the provided links, but if you hear something about the H2 database I'd really appreciate it.
Thanks again.
